services:
  camera_client:
    image: phadkesharanmatrixcomsec/django-camera-client-lite
    working_dir: /camera_client
    command: bash -c "pip install -r requirements.txt && python3 manage.py runserver 3000"
    ports:
      - "3000:3000"

  django_master:
    image: phadkesharanmatrixcomsec/django-master-lite
    working_dir: "/sps-master"
    command: bash -c "pip install -r requirements.txt && python3 manage.py runserver 8000"
    ports:
      - "8000:8000"
